### ISSUE TITLE
[Draft] Release management

### ISSUE THREAD

**Issue by fieg** [webcreate/conveyor#50]
Add command to release a new version:

```
conveyor release major|minor|patch
```

Configuration:

```
conveyor:
  release:
    tasks:
      - { type: shell, command: grunt build }
```
