### ISSUE TITLE
git pull needs a default branch configured (or specified)

### ISSUE THREAD

**Issue by pscheit** [webcreate/conveyor#7]
Hi again,

everything working now smoothely on unix.
But I get the following error:

```
Building 1.0.1 (staging) to ./build
 - Executing task Webcreate\Conveyor\Task\ExportTask                                                                                                      Exporting: 0%


  [Symfony\Component\Process\Exception\ProcessFailedException]
  The command "git pull 'origin'" failed.
  Exit Code: 1(General error)

  Output:
  ================


  Error Output:
  ================
  You asked to pull from the remote 'origin', but did not specify
  a branch. Because this is not the default configured remote
  for your current branch, you must specify a branch on the command line.

```

I have in my config:

``` yaml
conveyor:
  repository:
    type: git
    url: file:///var/local/git/enterframe/ssc.git
  targets:
    staging:
      transport:
        type: file
        host: pegasus.ps-webforge.net
        path: /var/local/www/ssc-test.ps-webforge.com
        user: www-data
        pass: empty
  build:
    dir: ./build
  deploy:
    strategy: releases
```

is this correct like this?
